POST http://dietplannerrds-env.eba-s2nrkgap.eu-north-1.elasticbeanstalk.com/foods/add
#POST http://localhost:5000/foods/add
Accept: application/json
Content-Type: application/json

{
  "id": null,
  "name": "ser",
  "weight": 200,
  "proteinPer100g": 27,
  "fatsPer100g": 8,
  "kcalPer100g": 400,
  "proteinTotal": 54,
  "fatsTotal": 16,
  "kcalTotal": 800
}

###
GET http://dietplannerrds-env.eba-s2nrkgap.eu-north-1.elasticbeanstalk.com/foods/all
Accept: application/json
Content-Type: application/json

###
#POST http://dietplannerrds-env.eba-s2nrkgap.eu-north-1.elasticbeanstalk.com/api/auth/signup
POST http://localhost:5000/api/auth/signup
Accept: application/json
Content-Type: application/json

{
  "username": "bartmj",
  "email": "root55343@gmail.com",
  "password": "adminadmin",
  "role": ["user", "mod", "admin"]
}

### SIGNUP MODERATOR
POST http://localhost:5000/api/auth/signup
Accept: application/json
Content-Type: application/json

{
  "username": "mod",
  "email": "mod@mail.pl",
  "password": "mod",
  "role": ["mod", "user"]
}

### SIGNUP USER 1
POST http://localhost:5000/api/auth/signup
Accept: application/json
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@wp.pl",
  "password": "user1",
  "role": ["user"]
}

### SIGNUP USER 2
POST http://localhost:5000/api/auth/signup
#Accept: application/json
Content-Type: application/json

{
  "username": "user023432733",
  "email": "user034332733@wp.pl",
  "password": "1234567890",
  "role": ["user"]
}

### TEST ALL
GET http://localhost:5000/api/test/all
Accept: application/json

### TEST USER
GET http://localhost:5000/api/test/user
Accept: application/json

### SIGN IN AS USER
POST http://localhost:5000/api/auth/signin
Accept: application/json
Content-Type: application/json

{
  "username": "root",
  "password": "admin123123"
}

### SIGN IN AS ADMIN
POST http://localhost:5000/api/auth/signin
Accept: application/json
Content-Type: application/json

{
  "username": "user023432733",
  "password": "1234567890"
}

### SIGN IN AS MODERATOR
POST http://localhost:5000/api/auth/signin
Accept: application/json
Content-Type: application/json

{
  "username": "bartmj_mod",
  "password": "mod"
}

### SIGN IN AS ADMIN
POST http://localhost:5000/api/auth/signin
Accept: application/json
Content-Type: application/json

{
  "username": "bartmj",
  "password": "adminadmin"
}

### See user content
GET http://localhost:5000/api/test/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyb290IiwiaWF0IjoxNjY4Nzk0MTEzLCJleHAiOjE2Njg4ODA1MTN9.vf8RDABWqq-bO6iBLb7Z0aOllZcaS0Id2SqBbD-7TCvEPR50uY7N_5UY9ICoVaVoDoiE1N2Q2XXX70OA9kxflw

### See admin content
GET http://localhost:5000/api/test/admin
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTY2ODM0NDUxNCwiZXhwIjoxNjY4NDMwOTE0fQ.IZcBv8G3Cbjqx-MymtlCb78I8QE5LWA7i_Yw3sHmrGwGBX1AROeA5ol24bjauUeK7zfWjah9kciAAfBQb-Iecg

### See moderator content
GET http://localhost:5000/api/test/mod
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJiYXJ0bWoiLCJpYXQiOjE2NjgzNDQyMzcsImV4cCI6MTY2ODQzMDYzN30.1pSkhWXFiswa0dFbT_h2LjMXF1pDiwTf0gAekmv98IUy0XSsaCnQTKjnfpb-2UagUqCvdcabh8w6Y4bt3ti64g

###
GET http://localhost:5000/favourites/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJiajkwIiwiaWF0IjoxNjY5MTI4NjgyLCJleHAiOjE2NjkyMTUwODJ9.Z1GLgsy5hKOws5k_LOvjcYVIVUj-c-Gj-KywI_CyqtFGlsZ8yjqtyr3tPYAfOsF4SPi3cnGSUXBmOa3pBz-CIQ