POST http://dietplannerrds-env.eba-s2nrkgap.eu-north-1.elasticbeanstalk.com/foods/add
#POST http://localhost:5000/foods/add
Accept: application/json
Content-Type: application/json

{
  "id": null,
  "name": "serko",
  "weight": 200,
  "proteinPer100g": 27,
  "fatsPer100g": 8,
  "kcalPer100g": 400,
  "proteinTotal": 54,
  "fatsTotal": 16,
  "kcalTotal": 800
}

###

GET http://dietplannerrds-env.eba-s2nrkgap.eu-north-1.elasticbeanstalk.com/foods/all
Accept: application/json
Content-Type: application/json

###
#POST http://dietplannerrds-env.eba-s2nrkgap.eu-north-1.elasticbeanstalk.com/api/auth/signup
POST http://localhost:5000/api/auth/signup
Accept: application/json
Content-Type: application/json

{
  "username": "bartmj",
  "email": "bj90@wp.pl",
  "password": "mod",
  "role": ["mod", "user"]
}



